Vue/outage card
uw-it-aca/myuw pull request #1966
Opened 2020-09-15 20:43 UTC by j0pp

2020-09-16 00:02 UTC, fanglinfang requested changes

2020-09-16 00:02 UTC, fanglinfang commented on myuw/static/vue/components/cards/outage.vue
> +        if (this.profileStatusCode) {
This should be instructed_course data

2020-09-16 00:05 UTC, fanglinfang commented
We also want to add unit tests with mock data.

2020-09-17 21:55 UTC, j0pp commented on myuw/static/vue/components/cards/outage.vue
> +        Limited data due to technical difficulties
Done by Char, thanks Char.

2020-09-17 21:56 UTC, j0pp commented on myuw/static/vue/components/cards/outage.vue
> +        if (this.profileStatusCode) {
Done

2020-09-22 17:08 UTC, j0pp commented
Can I get someone to review?

2020-09-22 17:50 UTC, SarthakSingh31 approved these changes

2020-09-24 18:55 UTC, fanglinfang approved these changes

2020-09-24 18:55 UTC, merged