Feature/muwm 4643
uw-it-aca/myuw pull request #2254
Opened 2021-01-28 20:59 UTC by fanglinfang

2021-02-11 23:08 UTC, fanglinfang commented on myuw/views/api/finance.py
> +            # response['tuition_due'] = str(get_tuition_due_date(request))
Skip this as we get the tuition due date from notice in JS.

2021-02-11 23:12 UTC, devights approved these changes

2021-02-16 17:35 UTC, lmanes requested changes
https://github.com/uw-it-aca/myuw/pull/2254/files/3021b21e6f2930d6b4fc651dce879acb7731d339#diff-2a52f1d1adf4602766c2340013cf99b3f5aa8607547e0d2214c97a65e4f183b5 

myuw/templates/handlebars/teaching/photo_list.html line 153 (on the new version)

We had to add this so the string would wrap in the photo grid version of the list. (Also had to increase the margin on the `last-child` `li` (https://github.com/uw-it-aca/myuw/pull/2254/files?file-filters%5B%5D=.html&file-filters%5B%5D=.less#diff-76b69079bb201d437f406e9a45b4e7118514e4fac1148f569711012a01f0e97dR71) 

However, if the student's name is two lines long and the pronoun string is two lines long, it's still truncating and cutting off text. 

![image](https://user-images.githubusercontent.com/940647/107718883-c2d62480-6c8b-11eb-8f64-cfe3886b144e.png)

I mocked this up by overriding as a different instructor -- someone with classes with lots of students, not just javerage. Then I went into dev tools and added a pronouns string into `div class="myuw-text-small"` for a whole bunch of students -- I used the same string for all of them: `She/her/hers; they/them/their/theirs/themself`

I tried adding padding and/or margin to several different elements (the `li`, the `div`) to see if it would fix this, but it didn't. I'm guessing there might be something about the overflowing text not actually increasing the height of the element, making it not behave like we expect? Just a guess. At this point it needs more investigation. Let me know if I can help guide you.

2021-02-22 22:35 UTC, kbui98 commented on myuw/templates/handlebars/teaching/photo_list.html
> +                            <div class="myuw-text-small" style="overflow-wrap: break-word;">{{pronouns}}</div>
Thanks for making those additions Lauren! I made edits to the pronouns wrapping on the photo grid page. This issue should be resolved now. I'll do another pull request!

2021-03-01 21:04 UTC, lmanes approved these changes
Looks good, thanks!

2021-06-28 19:36 UTC, closed without merging